sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /head_camera/depth_registered/points
   max_range: 5.0
   frame_subsample: 1
   point_subsample: 1
   padding_offset: 0.1
   padding_scale: 1.0
   filtered_cloud_topic: filtered_cloud
